service: mas-ial-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /ialsearch
          method: GET

plugins:
  - serverless-offline
