service: mas-ial-api

useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline
