service: mas-ial-api

useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  memorySize: 512
  timeout: 8
  lambdaHashingVersion: 20201221
  environment:
    API_URL: ${env:API_URL}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin