service: mas-ial-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'